INSERT INTO equipos (nombre, puntos, ciudad, nombre_dt)
VALUES ('Universidad Catolica',15, 'Santiago', 'Ariel Holan'),
       ('Union La Calera',12,'Baquedano', 'Juan Pablo Vojvoda'),
       ('Curico Unido',12, 'Curico', 'Nicolas Larcamon'),
       ('Universidad de Chile', 10, 'Santiago', 'Hernan Caputto'),
       ('Deportes Antofagasta', 10, 'Antofagasta', 'Juan Azconzabal'),
       ('Audax Italiano', 9, 'Santiago', 'Francisco Meneghini'),
       ('Everton', 8, 'Vina del Mar', 'Gustavo Daisasso'),
       ('Palestino', 8, 'Santiago', 'Ivo Basay'),
       ('Union Española', 7, 'Santiago', 'Ronald Fuentes'),
       ('Huachipato', 7, 'Talcahuano', 'Gustavo Florentin'),
       ('Cobresal', 7, 'El Salvador', 'Gustavo Huerta'), 
       ('Ohiggins', 4, 'Rancagua', 'Patricio Graff'),
       ('Deportes La Serena', 3, 'La Serena', 'Luis Marcoleta'),
       ('Colo Colo', 3, 'Santiago', 'Marcelo Espina'),
       ('Santiago Wanderers', 3, 'Valparaiso', 'Miguel Ramirez'),
       ('Universidad de Concepcion', 2, 'Concepcion', 'Francisco Bozan'),
       ('Coquimbo Unido', 1, 'Coquimbo', 'German Corengia'),
       ('Deportes Iquique', 1, 'Iquique', 'Jaime Vera Rodriguez');